# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run-test:

    docker:
      - image: circleci/node:latest      

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Install packages"
          command: "npm install"
      - run:
          name: "Compile"
          command: "cd src && ../node_modules/typescript/bin/tsc ts2jsii.ts --m commonjs"
      - run:
          name: "Test original.ts"
          command: "cd src && node ts2jsii.js ../test/original.ts"

workflows:
  test-workflow:
    jobs:
      - run-test

